# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0973d2f3505cb6f2c6c110d4f4f7f0d9c77d7df56fba45f179187c4ed5416f069f393cd9d2908be93488e117985b4d9c4f008db272c6596e1f9b56cd9ed4825e

test:
  secret_key_base: 7520b39f7068591b7f43221d6c41f58886d2bcfc92c0e674d8d90be4153efee71a7ba231dcd52c96a38ca54c42feef7a4ba00267ad7acd686a7316d2cb6cfbf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
